url: "http://installationissue.github.io"
# baseurl: "" # the subpath of your site, e.g. /blog
lang: en-AU

title: Arbitrary Analysis
author: Aye Aye
# email: ""
# description: ""

# bluesky_username: ""
github_username:  installationissue
github_link: https://github.com/InstallationIssue
linkedin_link: https://www.linkedin.com/in/angus-frost-se/

# Exclude from processing.
exclude:
  - README.md
  - .devcontainer/

topics:
  - title: Homelabbing
    path: homelab
  - title: Software Development
    path: software
  - title: Cyber Security
    path: cyber
  - title: Systems Administration
    path: sysadmin
  - title: Tabletop RPGs
    path: tabletop
  - title: General Critique
    path: critique